[workspace]
members = ["plugins/*"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = "2.0.0-alpha.6"
tauri-build = "2.0.0-alpha.3"
serde_json = "1"
thiserror = "1"

[workspace.package]
edition = "2021"
authors = [ "Tauri Programme within The Commons Conservancy" ]
license = "Apache-2.0 OR MIT"
rust-version = "1.64"

[patch.crates-io]
tauri = { git = "http://github.com/tauri-apps/tauri", branch = "next" }
tauri-build = { git = "http://github.com/tauri-apps/tauri", branch = "next" }