name: Test Rust

on:
  push:
    branches:
      - v1
      - v2
    paths:
      - ".github/workflows/test-rust.yml"
      - "plugins/*/src/**"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    branches:
      - v1
      - v2
    paths:
      - ".github/workflows/test-rust.yml"
      - "plugins/*/src/**"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/plugins-filter.yaml

  test:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: install webkit2gtk and libudev for [authenticator]
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libudev-dev

      - name: install openssl
        if: ${{ matrix.platform == 'windows-latest' && matrix.package == 'tauri-plugin-authenticator' }}
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md

      - uses: dtolnay/rust-toolchain@1.65.0

      - uses: Swatinem/rust-cache@v2

      - name: create dummy dist
        working-directory: examples/api
        run: mkdir dist

      - name: test ${{ matrix.package }}
        if: matrix.package != 'tauri-plugin-sql'
        run: cargo test --package ${{ matrix.package }} --all-targets

      - name: test ${{ matrix.package }} --all-features
        if: ${{ !contains(fromJSON('["tauri-plugin-http", "tauri-plugin-upload", "tauri-plugin-updater", "tauri-plugin-websocket", "tauri-plugin-sql"]'), matrix.package) }}
        run: cargo test --package ${{ matrix.package }} --all-targets --all-features

      - name: test ${{ matrix.package }} mysql
        if: matrix.package == 'tauri-plugin-sql'
        run: cargo test --package ${{ matrix.package }} --all-targets --no-default-features --features mysql

      - name: test ${{ matrix.package }} postgres
        if: matrix.package == 'tauri-plugin-sql'
        run: cargo test --package ${{ matrix.package }} --all-targets --no-default-features  --features postgres
